let rawData = {
  "audio_clips": [
    {
      "author": "Wazaa FM",
      "clipId": 8079588,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079588-devotional-hour-07-05-2022.mp3",
      "downloadURL": null,
      "duration": 3528.44,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": null,
      "image": null,
      "recordedAtTs": 1651890600,
      "staticLink": "https://audioboom.com/posts/8079588-devotional-hour-07-05-2022",
      "title": "Devotional Hour - 07.05.2022",
      "waveUrl": "https://images.theabcdn.com/i/w/9149054"
    },
    {
      "author": "Wazaa FM",
      "clipId": 8079587,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079587-avis-dc-12hr-07-05-2022.mp3",
      "downloadURL": null,
      "duration": 159.27,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": null,
      "image": null,
      "recordedAtTs": 1651912204,
      "staticLink": "https://audioboom.com/posts/8079587-avis-dc-12hr-07-05-2022",
      "title": "Avis DC 12hr - 07.05.2022 ",
      "waveUrl": "https://images.theabcdn.com/i/w/9149053"
    },
    {
      "author": "Wazaa FM",
      "clipId": 8079586,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079586-avis-dc-07hr-07-05-2022.mp3",
      "downloadURL": null,
      "duration": 198.741,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": null,
      "image": null,
      "recordedAtTs": 1651894200,
      "staticLink": "https://audioboom.com/posts/8079586-avis-dc-07hr-07-05-2022",
      "title": "Avis DC 07hr - 07.05.2022 ",
      "waveUrl": "https://images.theabcdn.com/i/w/9149052"
    },
    {
      "author": "Wazaa FM",
      "clipId": 8079585,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079585-avis-dc-19hr-06-05-2022.mp3",
      "downloadURL": null,
      "duration": 125.65,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": null,
      "image": null,
      "recordedAtTs": 1651851000,
      "staticLink": "https://audioboom.com/posts/8079585-avis-dc-19hr-06-05-2022",
      "title": "Avis DC 19hr - 06.05.2022 ",
      "waveUrl": "https://images.theabcdn.com/i/w/9149051"
    },
    {
      "author": "K rock Football",
      "clipId": 8079584,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079584-2022-afl-round-8-gws-giants-vs-geelong-3rd-quarter-highlights.mp3",
      "downloadURL": null,
      "duration": 46.7069,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": null,
      "image": null,
      "recordedAtTs": 1651912151,
      "staticLink": "https://audioboom.com/posts/8079584-2022-afl-round-8-gws-giants-vs-geelong-3rd-quarter-highlights",
      "title": "2022 - AFL ROUND 8 - GWS GIANTS vs. GEELONG: 3rd Quarter Highlights",
      "waveUrl": "https://images.theabcdn.com/i/w/9149050"
    },
    {
      "author": "WSJ This Morning",
      "clipId": 8079583,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079583-this-weekend-with-gordon-deal-may-07-2022.mp3",
      "downloadURL": null,
      "duration": 2196.11,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>American consumers are shopping, traveling, and working out like it's 2019, the race to dominate the new battery economy, and there are 19 living Kentucky Derby winners.</div>",
      "image": null,
      "recordedAtTs": 1651911622,
      "staticLink": "https://audioboom.com/posts/8079583-this-weekend-with-gordon-deal-may-07-2022",
      "title": "This Weekend with Gordon Deal May 07, 2022",
      "waveUrl": "https://images.theabcdn.com/i/w/9149049"
    },
    {
      "author": "Perdidos en El Eter",
      "clipId": 8079580,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079580-perdidos-en-el-eter-481-sopapo-oriental-the-paper-tigers.mp3",
      "downloadURL": null,
      "duration": 5520.01,
      "embedDisabled": false,
      "seasonNumber": 20,
      "episodeNumber": 481,
      "formattedDescription": "<p>&amp;iexcl;Primer Sopapo del a&amp;ntilde;o! Eze y MaGnUs hacen la RE: se&amp;ntilde;a de The Paper Tigers, una pel&amp;iacute;cula que mezcla artes marciales, drama, y comedia en una sola. Tres cuarentones, hermanos adoptivos y prodigios del kung-fu en su adolescencia, se re&amp;uacute;nen despu&amp;eacute;s de d&amp;eacute;cadas de alejamiento cuando su anciano maestro muere de manera misteriosa. &amp;iquest;Fue asesinado? Habilidades oxidadas, rodillas lesionadas, y relaciones rotas deben ser reparadas o toleradas para llegar al fondo del asunto. Y por supuesto, sopapos y patadas chinas. Con m&amp;uacute;sica de Andrew Tsai, Weird Al Yankovic, y Survivor. Pr&amp;oacute;ximo programa: Moon Knight.</p>\n<div>¡Primer Sopapo del año! Eze y MaGnUs hacen la RE: seña de The Paper Tigers, una película que mezcla artes marciales, drama, y comedia en una sola. Tres cuarentones, hermanos adoptivos y prodigios del kung-fu en su adolescencia, se reúnen después de décadas de alejamiento cuando su anciano maestro muere de manera misteriosa. ¿Fue asesinado? Habilidades oxidadas, rodillas lesionadas, y relaciones rotas deben ser reparadas o toleradas para llegar al fondo del asunto. Y por supuesto, sopapos y patadas chinas.</div><div>Con música de Andrew Tsai, Weird Al Yankovic, y Survivor.</div><div>Próximo programa: Moon Knight.</div>",
      "image": {
        "id": 39197305,
        "averageColor": "#c54613",
        "format": "jpg"
      },
      "recordedAtTs": 1651906636,
      "staticLink": "https://audioboom.com/posts/8079580-perdidos-en-el-eter-481-sopapo-oriental-the-paper-tigers",
      "title": "Perdidos En El Éter #481: Sopapo Oriental - The Paper Tigers",
      "waveUrl": "https://images.theabcdn.com/i/w/9149047"
    },
    {
      "author": "K rock Football",
      "clipId": 8079579,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079579-2022-afl-round-8-gws-giants-vs-geelong-2nd-quarter-highlights.mp3",
      "downloadURL": null,
      "duration": 45.7143,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": null,
      "image": null,
      "recordedAtTs": 1651909046,
      "staticLink": "https://audioboom.com/posts/8079579-2022-afl-round-8-gws-giants-vs-geelong-2nd-quarter-highlights",
      "title": "2022 - AFL ROUND 8 - GWS GIANTS vs. GEELONG: 2nd Quarter Highlights",
      "waveUrl": "https://images.theabcdn.com/i/w/9149046"
    },
    {
      "author": "स्पोर्ट्स बुलेटिन",
      "clipId": 8079577,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079577-ipl-podcast.mp3",
      "downloadURL": null,
      "duration": 491.136,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": 168,
      "formattedDescription": "<div>आईपीएल 2022 में चेन्नई की टीम भले ही अब औपचारिक तौर पर प्‍लेऑफ से बाहर होने की कगार पर है, लेकिन महेन्द्र सिंह धोनी अब आधिकारिक तौर पर चेन्नई के बॉस हो गए हैं. धोनी ने रविंद्र जडेजा के कप्तानी छोड़ने के बाद टीम की कमान फिर से संभाल ली है और सीजन के पहले ही मैच में उन्होंने बतौर कप्तान टीम को जीत भी दिला दी.</div>",
      "image": null,
      "recordedAtTs": 1651908559,
      "staticLink": "https://audioboom.com/posts/8079577-ipl-podcast",
      "title": "IPL Podcast: शुरू हुआ प्लेआफ के लिए आईपीएल का निर्णायक दौर, मुहाने पर खड़ी गुजरात को मुंबई ने दिया बड़ा झटका",
      "waveUrl": "https://images.theabcdn.com/i/w/9149044"
    },
    {
      "author": "The Sideline View",
      "clipId": 8079576,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079576-adam-ellerton-bowls.mp3",
      "downloadURL": null,
      "duration": 384.784,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": 66,
      "formattedDescription": "<div>Adam Ellerton Joined Robbo on The Sideline View with all the latest on Bowls...</div>",
      "image": null,
      "recordedAtTs": 1651907820,
      "staticLink": "https://audioboom.com/posts/8079576-adam-ellerton-bowls",
      "title": "Adam Ellerton - Bowls",
      "waveUrl": "https://images.theabcdn.com/i/w/9149043"
    },
    {
      "author": "K rock Football",
      "clipId": 8079575,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079575-2022-afl-round-8-gws-giants-vs-geelong-1st-quarter-highlights.mp3",
      "downloadURL": null,
      "duration": 52.689,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": null,
      "image": null,
      "recordedAtTs": 1651907110,
      "staticLink": "https://audioboom.com/posts/8079575-2022-afl-round-8-gws-giants-vs-geelong-1st-quarter-highlights",
      "title": "2022 - AFL ROUND 8 - GWS GIANTS vs. GEELONG: 1st Quarter Highlights",
      "waveUrl": "https://images.theabcdn.com/i/w/9149042"
    },
    {
      "author": "Latest Stories from The Associated Press",
      "clipId": 8079574,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079574-update-on-the-latest-sports.mp3",
      "downloadURL": null,
      "duration": 120.048,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>The 76ers and Mavs win at home, the Bruins break the ice against the Hurricanes, the Maple Leafs regain control of their series, the Wild win their second straight and the Oilers batter the Kings. AP correspondent Dave Ferry reports.</div>",
      "image": null,
      "recordedAtTs": 1651905745,
      "staticLink": "https://audioboom.com/posts/8079574-update-on-the-latest-sports",
      "title": "Update on the latest sports",
      "waveUrl": "https://images.theabcdn.com/i/w/9149040"
    },
    {
      "author": "DOWN2EARTH PODCAST",
      "clipId": 8079573,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079573-the-first-influencer.mp3",
      "downloadURL": null,
      "duration": 1494.92,
      "embedDisabled": false,
      "seasonNumber": 4,
      "episodeNumber": null,
      "formattedDescription": "<div>in this episode I get Down2earth about a historical American religious figure Elder Lightfoot Solomon Michaux and his Links to the FBI and his discredited focus on Martin Luther king. His rise and fall and his comparisons now as a would be social media influencer as he was one of the first to have a weekly television show broadcast all over America and the world </div>",
      "image": {
        "id": 39197270,
        "averageColor": "#010102",
        "format": "jpg"
      },
      "recordedAtTs": 1651904934,
      "staticLink": "https://audioboom.com/posts/8079573-the-first-influencer",
      "title": "The first influencer ",
      "waveUrl": "https://images.theabcdn.com/i/w/9149041"
    },
    {
      "author": "The Sideline View",
      "clipId": 8079572,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079572-mark-alabakov-bendigo-braves-basketball.mp3",
      "downloadURL": null,
      "duration": 413.309,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": 66,
      "formattedDescription": "<div>Mark Alabakov - Bendigo Braves Basketball Head Women's Coach joined Robbo ahead of tonight's clash against Ballarat, and tomorrow's Pink game...</div>",
      "image": null,
      "recordedAtTs": 1651906529,
      "staticLink": "https://audioboom.com/posts/8079572-mark-alabakov-bendigo-braves-basketball",
      "title": "Mark Alabakov - Bendigo Braves Basketball",
      "waveUrl": "https://images.theabcdn.com/i/w/9149039"
    },
    {
      "author": "The Sideline View",
      "clipId": 8079571,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079571-james-rouel-bendigo-tennis.mp3",
      "downloadURL": null,
      "duration": 337.711,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": 66,
      "formattedDescription": "<div>James Rouel from Bendigo Tennis joined Robbo on The Sideline View to tell Robbo about a new on-line initiative to get more people playing...</div>",
      "image": null,
      "recordedAtTs": 1651906403,
      "staticLink": "https://audioboom.com/posts/8079571-james-rouel-bendigo-tennis",
      "title": "James Rouel Bendigo Tennis",
      "waveUrl": "https://images.theabcdn.com/i/w/9149038"
    },
    {
      "author": "SFMSports High School",
      "clipId": 8079570,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079570-pierz-pioneers-vs-pequot-lakes-patriots-softball-2022.mp3",
      "downloadURL": null,
      "duration": 7123.72,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": 550,
      "formattedDescription": "<div>The Pioneers lost 7-2 to the undefeated Patriots in Pierz as they were unable to generate much offense against Kaitlyn Geschwill, who had thrown no-hitters in her last 3 games.  She would have made it 4 in a row if not for a 1st inning single from Brenna Dickmann.  A highlight for the Pioneers was 2 sparking defensive plays turned in by 2nd baseman Kenna Otte.</div>",
      "image": {
        "id": 39197254,
        "averageColor": "#b6b0ad",
        "format": "jpg"
      },
      "recordedAtTs": 1651906328,
      "staticLink": "https://audioboom.com/posts/8079570-pierz-pioneers-vs-pequot-lakes-patriots-softball-2022",
      "title": "Pierz Pioneers vs Pequot Lakes Patriots Softball 2022",
      "waveUrl": "https://images.theabcdn.com/i/w/9149037"
    },
    {
      "author": "The Sideline View",
      "clipId": 8079569,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079569-geoff-cramer-fishing.mp3",
      "downloadURL": null,
      "duration": 421.016,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": 66,
      "formattedDescription": "<div>Geoff Cramer joined Robbo with all the latest Fishing news on The Sideline View...</div>",
      "image": null,
      "recordedAtTs": 1651906301,
      "staticLink": "https://audioboom.com/posts/8079569-geoff-cramer-fishing",
      "title": "Geoff Cramer - Fishing",
      "waveUrl": "https://images.theabcdn.com/i/w/9149036"
    },
    {
      "author": "REVOLT BLACK NEWS",
      "clipId": 8079568,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079568-the-elon-effect-and-the-future-of-black-twitter-the-black-estate-debacle-and-black-women-findin.mp3",
      "downloadURL": null,
      "duration": 2534.77,
      "embedDisabled": false,
      "seasonNumber": 3,
      "episodeNumber": 10,
      "formattedDescription": "<div>REVOLT Black News investigates the deep rooted history inside the White House’s effort to dismantle racial bias in the home lending and appraisal process and promote generational wealth creation through homeownership; Twitter's Board to accept Elon Musk’s offer to purchase Twitter and convert it into a private entity, and more.</div>",
      "image": {
        "id": 39197246,
        "averageColor": "#524141",
        "format": "jpg"
      },
      "recordedAtTs": 1651870800,
      "staticLink": "https://audioboom.com/posts/8079568-the-elon-effect-and-the-future-of-black-twitter-the-black-estate-debacle-and-black-women-findin",
      "title": "The Elon Effect and The Future of Black Twitter, The Black Estate Debacle, and Black Women Finding Love Outside The Race",
      "waveUrl": "https://images.theabcdn.com/i/w/9149035"
    },
    {
      "author": "Motorsport.com Formule 1-podcast",
      "clipId": 8079567,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079567-f1-update-slechte-start-voor-verstappen-in-miami-comeback-voor-mercedes.mp3",
      "downloadURL": null,
      "duration": 883.424,
      "embedDisabled": false,
      "seasonNumber": 2,
      "episodeNumber": 27,
      "formattedDescription": "<div>De eerste Formule 1-actiedag op het Miami International Autodrome ging absoluut niet onopgemerkt voorbij. Vele spins, een verrassend goed Mercedes en problemen voor Max Verstappen. Hoe kostbaar is de gemiste rijtijd voor de Red Bull-coureur en geeft de Mercedes-opleving ook hoop op structurele verbetering? Dit en nog veel meer bespreken Leonie Oude Elferink en Ronald Vording in een nieuwe F1-update.<br><br>\n</div>",
      "image": null,
      "recordedAtTs": 1651905109,
      "staticLink": "https://audioboom.com/posts/8079567-f1-update-slechte-start-voor-verstappen-in-miami-comeback-voor-mercedes",
      "title": "F1-update: Slechte start voor Verstappen in Miami, comeback voor Mercedes?",
      "waveUrl": "https://images.theabcdn.com/i/w/9149034"
    },
    {
      "author": "RIVER1467 - The Home Run",
      "clipId": 8079566,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8079566-brett-millington-mildura-regional-development.mp3",
      "downloadURL": null,
      "duration": 380.458,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": 41,
      "formattedDescription": null,
      "image": null,
      "recordedAtTs": 1651905029,
      "staticLink": "https://audioboom.com/posts/8079566-brett-millington-mildura-regional-development",
      "title": "Brett Millington Mildura Regional Development",
      "waveUrl": "https://images.theabcdn.com/i/w/9149033"
    }
  ]
}

module.exports.rawData = rawData;
