let rawData = {
  "audio_clips": [
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8038745,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8038745-episode-302-albert-fish-part-1.mp3",
      "downloadURL": null,
      "duration": 4899.76,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>This is such a highly requested case that Alaina decided to take one for the team and dive deep into the world that was Albert Fish. Albert Fish had an incredibly abusive childhood starting from when he was 5 years old and had to be placed into an orphanage. He experienced all kinds of torture and abuse and it was there that he realized he was aroused by not only the pain he was suffering but the pain inflicted upon others. In part one we’ll cover Fish’s first crimes, including his first murder which was the brutal slaying of Francis McDonnell, an eight year old boy. <br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.buzzfeednews.com/article/christinekenneally/orphanage-death-catholic-abuse-nuns-st-josephs\">\"We Saw Nuns Kill Children: The Ghosts of St. Joseph's Orphanage\" by Christine Kenneally</a> <br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Deranged-Shocking-Americas-Fiendish-Killer/dp/0671025457/ref=sr_1_4?keywords=albert+fish+book&amp;qid=1645989535&amp;sprefix=Albert+fish+%2Caps%2C101&amp;sr=8-4\">Deranged by Harold Shechter</a> <br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Confessions-Cannibal-Shocking-Depraved-Killer/dp/1535212667/ref=sr_1_5?keywords=albert+fish+book&amp;qid=1645989535&amp;sprefix=Albert+fish+%2Caps%2C101&amp;sr=8-5\">Confessions of a Cannibal by Robert Keller </a> <br><br>\n</div><div>As always, a huge thank you to our sponsors:<br><br>GoodRX: for simple, smart savings on your prescriptions, check GoodRx. Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://GoodRX.com/morbid\">GoodRX.com/morbid</a><br><br>Peloton: Visit <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://onepeloton.com\">onepeloton.com</a> to learn more<br><br>MeUndies: To get 15% off your first order, free shipping, and a 100% satisfaction guarantee, go to  <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://MeUndies.com/MORBID\">MeUndies.com/MORBID</a><br><br>Blueland: Right now, you can get 20% off your first order when you go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://Blueland.com/MORBID\">Blueland.com/MORBID</a>\n</div>",
      "image": null,
      "recordedAtTs": 1645999380,
      "staticLink": "https://audioboom.com/posts/8038745-episode-302-albert-fish-part-1",
      "title": "Episode 302: Albert Fish Part 1",
      "waveUrl": "https://images.theabcdn.com/i/w/9105541"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8040810,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8040810-episode-303-albert-fish-part-2.mp3",
      "downloadURL": null,
      "duration": 5858.1,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>Congratulations, you’ve made it to part two which means your psyche is STRONG. Albert fish continues to be a wretched individual throughout part two. The gray man continues abducting and murdering two more children, earning him a new name, The Boogyman. Luckily toward the end we’ll inch our way closer to an arrest but boy does it get more and more disturbing along the way.<br><br>\n</div><div>\n<a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Deranged-Shocking-Americas-Fiendish-Killer/dp/0671025457/ref=sr_1_4?keywords=albert+fish+book&amp;qid=1645989535&amp;sprefix=Albert+fish+%2Caps%2C101&amp;sr=8-4\">Deranged by Harold Shechter<br></a><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Confessions-Cannibal-Shocking-Depraved-Killer/dp/1535212667/ref=sr_1_5?keywords=albert+fish+book&amp;qid=1645989535&amp;sprefix=Albert+fish+%2Caps%2C101&amp;sr=8-5\">Confessions of a Cannibal by Robert Keller <br></a><br><strong>As always, thank you to our sponsors:</strong>\n</div><div>\n<br><strong>HelloFresh: </strong>Get 16 free meals, plus three free gifts with code Morbid16 at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://hellofresh.com/morbid16\">hellofresh.com/morbid16</a>\n</div><div><br></div><div>\n<strong>Everlane: </strong>Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://everlane.com/morbid\">everlane.com/morbid</a> and sign up for 10% off your first order</div><div><br></div><div>\n<strong>ShipStation: </strong>Use our offer code, Morbid to get a 60 day free trial.</div><div><br></div><div>\n<strong>American Home Shield: </strong>Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://AHS.com/Morbid\">AHS.com/Morbid</a> now to save $50</div><div>\n<br><strong>Thirdlove: </strong>Right now you can get 20% off your first order at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://thirdlove.com/morbid\">thirdlove.com/morbid</a>\n</div>",
      "image": null,
      "recordedAtTs": 1646258943,
      "staticLink": "https://audioboom.com/posts/8040810-episode-303-albert-fish-part-2",
      "title": "Episode 303: Albert Fish Part 2 ",
      "waveUrl": "https://images.theabcdn.com/i/w/9107776"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8033496,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8033496-episode-299-the-horrific-murder-of-dorothy-eggers.mp3",
      "downloadURL": null,
      "duration": 5253.13,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>When Arthur Eggers walked into the police station to report his wife Dorothy missing, there were a few things about his story that just didn’t quite add up. He had her height off by about 5 inches and he said he was reporting her missing even though he knew she most likely ran off with a truck driver (!!!!) The police were quite concerned though, because they had an unidentified, HEADLESS body, and now they were thinking it could be Arthur’s wife. This tale will take you on so many different rides, you know what to do. Hold on. To. Your. Butts and potentially your food coloring. <br><br>Shout out to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://Newspapers.com\">Newspapers.com</a> for having old awesome articles!<br><br>As always, thank you to our sponsors:<br><br>HelloFresh: Get sixteen free meals, plus three gifts, with code morbid16 at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HELLOFRESH.com/morbid16\">HELLOFRESH.com/morbid16</a>.<br><br>Scribd: Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://try.scribd.com/MATCP\">try.scribd.com/MATCP</a> to get your first two months for less than $1.<br><br>Simplisafe: Head to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://SIMPLISAFE.com/morbid\">SIMPLISAFE.com/morbid</a> to claim a free indoor security camera plus 20% off with Interactive Monitoring<br><br>Modern Fertility: Right now, Modern Fertility is offering our listeners $20 off the test when you go to Modern <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://Fertility.com/MORBID\">Fertility.com/MORBID</a><br><br>BetterHelp: This podcast is sponsored by BetterHelp and Morbid listeners get 10% off their first month at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BetterHelp.com/morbid\">BetterHelp.com/morbid</a>\n</div>",
      "image": null,
      "recordedAtTs": 1645129320,
      "staticLink": "https://audioboom.com/posts/8033496-episode-299-the-horrific-murder-of-dorothy-eggers",
      "title": "Episode 299: The Horrific Murder of Dorothy Eggers",
      "waveUrl": "https://images.theabcdn.com/i/w/9100038"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 7992710,
      "clipURLPriorToLoading": "https://audioboom.com/posts/7992710-episode-284-dorothea-puente-part-2.mp3",
      "downloadURL": null,
      "duration": 4589.27,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>Dorothea is back back back again and she’s eviler than ever. She’s befriending people only to murder them slowly, she’s pretending to fall inlove with a man from her actual prison cell only to murder him and throw him in a river bank. BUT have no fear because this woman does get caught, and she gets got in a pretty poetic way if you ask us!<br><br>For anyone with information regarding Michael Vaughan’s disappearance <br>Call Fruitland PD Dispatch 2086426006<br>OR <br>Email: findmichael@fruitland.org<br><br>Some fascinating books used:<br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Bone-Garden-Chilling-Female-Serial-ebook/dp/B07K1MML3K/ref=tmm_kin_swatch_0?_encoding=UTF8&amp;qid=1638583603&amp;sr=8-1-spons#customerReviews\">The Bone Garden by William P. Wood</a><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Buried-Beneath-Boarding-House-Exploitation/dp/1695085574/ref=sr_1_1_sspa?crid=25PSYJJCUP8G2&amp;keywords=buried+beneath+the+boarding+house&amp;qid=1638751230&amp;sprefix=buried+bene%2Caps%2C173&amp;sr=8-1-spons&amp;psc=1&amp;spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyVVdDTUtZU0k2Sk9QJmVuY3J5cHRlZElkPUEwMTU5ODM5T1NKU1pUWThSMTk1JmVuY3J5cHRlZEFkSWQ9QTAxMDEzMjAxOEoyVUFCRDhTM0w5JndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==\">Buried Beneath The Boarding House by Ryan Green</a><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Corpse-Collector-Dorothea-Boarding-Explicit-ebook/dp/B09MJ4M1PL/ref=sr_1_2?keywords=corpse+collector&amp;qid=1638751269&amp;sr=8-2\">Corpse Collector by Genova Ortiz</a><br><br>As always, thank you to our sponsors:<br><br>HelloFresh: Get up to fourteen free meals—plus, three free gifts!—with code morbid14 at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HelloFresh.com/morbid14\">HelloFresh.com/morbid14</a><br><br>MasterClass: This holiday, give one annual membership and get one free! Go to<br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://MASTERCLASS.com/MORBID\">MASTERCLASS.com/MORBID</a> today.<br><br>BestFiends: Download Best Fiends FREE today on the App Store or Google Play.<br><br>SimpliSafe: Take advantage of SimpliSafe’s Holiday deals and get 40% off your new home security system by visiting <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://SIMPLISAFE.com/morbid\">SIMPLISAFE.com/morbid</a>.<br> <br>PrettyLitter: Go to Pretty Litter dot com and use promo code morbid for 20% off your first order.</div>",
      "image": null,
      "recordedAtTs": 1638901660,
      "staticLink": "https://audioboom.com/posts/7992710-episode-284-dorothea-puente-part-2",
      "title": "Episode 284: Dorothea Puente Part 2 ",
      "waveUrl": "https://images.theabcdn.com/i/w/9056268"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8047835,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8047835-episode-306-the-st-osyth-witch-trials.mp3",
      "downloadURL": null,
      "duration": 4884.29,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>\n<br>Alaina brings us the true story of the The St Osyth Witch trials this week. It all starts with a \"naughty named\" woman, Ursula, potentially causing the lameness of another woman called Grace. Causing the lameness of another was grounds for being charged with the very serious felony of Witchcraft, and really it all went downhill from there. In the end fourteen were accused, two were hanged and many more died in prison. <br><br>\n</div><div>The book and pamphlet used as a source for the case: <br><br>\n</div><div>\n<a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Englands-Witchcraft-Trials-Willow-Winsham-ebook/dp/B07GJGKKFJ/ref=sr_1_1?crid=1SBCEHNOT86HP&amp;keywords=witch+trials+of+England+willow&amp;qid=1647368767&amp;sprefix=witch+trials+of+england+willow%2Caps%2C62&amp;sr=8-1\">England's Witchcraft Trials by Willow Winsham</a> <br><br>\n</div><div>\n<a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://www.witchtrials.co.uk/osyth.html\"><em>A true and iust recorde, of the information, examination and confession of all the witches, taken at S. Ofes in the countie of Essex whereof some were executed, and other some entreated according to the determination of lawe. Wherein all men may see what a pestilent people witches are, and how vnworthy to lyue in a Christian Commonwealth. Written orderly, as the cases were tryed by euidence, by W. W</em></a> <br><br>As always, thank you to our sponsors:<br><br>HelloFresh: Get sixteen free meals, plus three gifts, with code morbid16 at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HELLOFRESH.com/morbid16\">HELLOFRESH.com/morbid16</a>.<br><br>Simplisafe: Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://SIMPLISAFE.com/morbid\">SIMPLISAFE.com/morbid</a>  today and claim a free indoor security camera plus 20% off with Interactive Monitoring.<br><br>BetterHelp: This podcast is sponsored by BetterHelp and Morbid listeners get 10% off their first<br>month at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BetterHelp.com/morbid\">BetterHelp.com/morbid</a><br><br>Noom: Sign up for your trial at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://Noom.com/MORBID\">Noom.com/MORBID</a><br><br>\n</div>",
      "image": null,
      "recordedAtTs": 1647381360,
      "staticLink": "https://audioboom.com/posts/8047835-episode-306-the-st-osyth-witch-trials",
      "title": "Episode 306: The St. Osyth Witch Trials",
      "waveUrl": "https://images.theabcdn.com/i/w/9115223"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8043250,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8043250-episode-305-albert-fish-part-4.mp3",
      "downloadURL": null,
      "duration": 4871.96,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>The end is here! Alaina’s psyche shall repair over the course of the next week and so will yours. The final installment of this series will cover Albert’s trial and ultimately his own death. See you later this week with some light Listener Tales!<br><br>\n</div><div>\n<a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Deranged-Shocking-Americas-Fiendish-Killer/dp/0671025457/ref=sr_1_4?keywords=albert+fish+book&amp;qid=1645989535&amp;sprefix=Albert+fish+%2Caps%2C101&amp;sr=8-4\">Deranged by Harold Shechter<br></a><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Confessions-Cannibal-Shocking-Depraved-Killer/dp/1535212667/ref=sr_1_5?keywords=albert+fish+book&amp;qid=1645989535&amp;sprefix=Albert+fish+%2Caps%2C101&amp;sr=8-5\">Confessions of a Cannibal by Robert Keller </a><br><br>\n</div><div>As always, thank you to our sponsors:<br><br>BestFiends: Shop now and get up to 30% off fire pits all month long, AND use promo code MORBID at checkout to get an extra $20 off.<br><br>Prose: Take your FREE in-depth hair consultation and get 15% off your first order today! Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://Prose.com/morbid\">Prose.com/morbid</a><br><br>Daily Harvest: Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://DAILYHARVEST.com/morbid\">DAILYHARVEST.com/morbid</a> to get up to forty dollars off your first box!<br><br>MVMT: Join the MVMT and get 15% off today — with FREE SHIPPING and FREE RETURNS — by going to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://MVMT.COM/MORBID\">MVMT.COM/MORBID</a>\n</div>",
      "image": null,
      "recordedAtTs": 1646694300,
      "staticLink": "https://audioboom.com/posts/8043250-episode-305-albert-fish-part-4",
      "title": "Episode 305: Albert Fish Part 4",
      "waveUrl": "https://images.theabcdn.com/i/w/9110358"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8052435,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8052435-episode-308-the-case-of-the-butterfly-man.mp3",
      "downloadURL": null,
      "duration": 4001.85,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>\n<br>Alaina brings us the news of her first novel (Ash is so fucking proud) <em>The Butcher and the Wren</em>(<a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://tinyurl.com/thebutcherandthewren\">available to pre-order now!!!!</a>) and also brings us the case of The Butterfly Man. Frank Lockhart was known around town as a pretty normal dude who tried to sell handmade butterfly hair clips to make some extra cash. He and his wife had fallen on hard times and were living in a shelter under an overpass. Little did the sweet townspeople know, this man had escaped prison where he was serving a life sentence for assaulting a young girl and would soon strike again. <br><br>\n</div><div>\n<br>**********<a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://tinyurl.com/thebutcherandthewren\">Pre-Order <em>The Butcher and the Wren </em>here!!!!</a> *************</div><div>\n<br>As always, thank you to our sponsors:<br><br>American Home Shield: Right now, MORBID listeners can take $50 off their most comprehensive plans ever. Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://ahs.com/MORBID\">ahs.com/MORBID</a> now to SAVE $50.<br><br>Thrive: Join today to get 40% off your first order AND a FREE gift worth over $50 at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://ThriveMarket.com/MORBID\">ThriveMarket.com/MORBID</a><br><br>Firstleaf: Join today and you’ll get 6 bottles of wine for $29.95 and free shipping! Just go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://TRYFirstleaf.com/MORBID\">TRYFirstleaf.com/MORBID</a><br><br>BetterHelp: This podcast is sponsored by BetterHelp and Morbid listeners get 10% off their first<br>month at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BetterHelp.com/morbid\">BetterHelp.com/morbid</a><br><br>Liquid IV: You can get 25% off when you go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://LIQUIDIV.COM\">LIQUIDIV.COM</a> and use code MORBID at checkout</div>",
      "image": null,
      "recordedAtTs": 1647966441,
      "staticLink": "https://audioboom.com/posts/8052435-episode-308-the-case-of-the-butterfly-man",
      "title": "Episode 308: The Case of the Butterfly Man ",
      "waveUrl": "https://images.theabcdn.com/i/w/9120002"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8036162,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8036162-episode-300-the-mysterious-murder-of-christa-helm.mp3",
      "downloadURL": null,
      "duration": 4826.55,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>Ash hadn’t done an old Hollywood case in a while, so upon finding this one dove right in! Christa Helm was born in Milwaukee but knew that she was destined for a life much bigger. She would tell anyone who would listen that she wanted to be a star and no one doubted her ability to get there. Christa moved out to Hollywood to make it big, and while she had some success along the way, the biggest story surrounding Christa would be her murder. Unfortunately Christa’s murder still remains unsolved but it is a wild ride trying to make sense of it all!<br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.whokilledchristahelm.com/christasstory\">https://www.whokilledchristahelm.com/christasstory</a><br><br>As always, thank you to our sponsors:<br><br>HelloFresh: Get sixteen free meals, plus three gifts, with code morbid16 at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HELLOFRESH.com/morbid16\">HELLOFRESH.com/morbid16</a><br><br>Rothy’s: Hit the new year in stride with a fresh pair of Rothy’s. New customers get $20 off your first purchase at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://rothys.com/MORBID\">rothys.com/MORBID</a><br><br>Purple: Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://Purple.com/morbid10\">Purple.com/morbid10</a> and use code morbid10. For a limited time you can get 10% off any order of $200 or more.<br><br>Daily Harvest: Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://DAILYHARVEST.com/morbid\">DAILYHARVEST.com/morbid</a> to get up to forty dollars off your first box!<br><br>BetterHelp: This podcast is sponsored by BetterHelp and Morbid listeners get 10% off their first month at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BetterHelp.com/morbid\">BetterHelp.com/morbid</a>\n</div>",
      "image": null,
      "recordedAtTs": 1645568640,
      "staticLink": "https://audioboom.com/posts/8036162-episode-300-the-mysterious-murder-of-christa-helm",
      "title": "Episode 300: The Mysterious Murder of Christa Helm",
      "waveUrl": "https://images.theabcdn.com/i/w/9108228"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8073091,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8073091-the-mysterious-disappearance-of-dorothy-arnold-part-2.mp3",
      "downloadURL": null,
      "duration": 5088.79,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>In part one we learned about the circumstances surrounding Dorothy Arnold’s disappearance. By all means it just seemed like she went out for a day of shopping and then disappeared into thin air. In part 2 Alaina delivers some theories that have been visited over the past hundred years and we both come to our own conclusion on what the heck happened to Dorothy Arnold. What’s your conclusion?<br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.instagram.com/justiceforyanira/\">Instagram page for information on the case of Yanira Cedillos</a> </div><div><br></div><div>As always, thank you to our sponsors:<br><br>Page 1 Books: First-time subscribers get 15% off with the code MORBID at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://page1books.com\">page1books.com</a> <br><br>Everlane: Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://everlane.com/MORBID\">everlane.com/MORBID</a> and sign up for 10% off your first order<br><br>HelloFresh: Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HelloFresh.com/morbid16\">HelloFresh.com/morbid16</a> and use code morbid16 for up to 16 free meals AND 3 free gifts!<br><br>Babbel: Right now, save up to 60% off your subscription when you go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BABBEL.com/MORBID\">BABBEL.com/MORBID</a><br><br>Good RX: For simple, smart savings on your prescriptions, check GoodRx. Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://GoodRX.com/morbid\">GoodRX.com/morbid</a>\n</div>",
      "image": null,
      "recordedAtTs": 1651007820,
      "staticLink": "https://audioboom.com/posts/8073091-the-mysterious-disappearance-of-dorothy-arnold-part-2",
      "title": "The Mysterious Disappearance of Dorothy Arnold Part 2",
      "waveUrl": "https://images.theabcdn.com/i/w/9141883"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8024066,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8024066-episode-296-james-rodney-hicks-part-1.mp3",
      "downloadURL": null,
      "duration": 4789.21,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>In 1977 Jennie Hicks seemingly vanished from her home in Carmel Maine, leaving her two children behind with her husband James Hicks... at least that was James’ story. Those who knew Jennie were adamant that there was no way she would have left her children, especially not with her husband who was known to physically abuse her. When law enforcement didn’t seem interested in actually investigating Jennie’s disappearance that left James free to do as he pleased, and a few years later would leave another young mother missing and presumed dead. <br><br>\n</div><div>Great source for this case: <a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Tragedy-North-Woods-Murders-James-ebook/dp/B00XRCXSCU\">Tragedy In The North Woods by Trudy Irene</a> </div><div>\n<br><strong>As always, thank you to our sponsors:</strong>\n</div><div><br></div><div>\n<strong>Shipstation: </strong>Use code, MORBID, to get a 60-day free trial! Just go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://ShipStation.com\">ShipStation.com</a>, click on the microphone at the top of the page, and type in MORBID.</div><div><br></div><div>\n<strong>LiquidIV: </strong>Get 25% off when you go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://liquidiv.com/\">LIQUIDIV.COM</a> and use code MORBID at checkout</div><div><br></div><div>\n<strong>HunterDouglas: </strong>Visit <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HunterDouglas.com/MORBID\">HunterDouglas.com/MORBID</a> for your free design</div><div>\n<br><strong>Everlane: </strong>Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://everlane.com/MORBID\">everlane.com/MORBID</a> and sign up for 10% off your first order.</div>",
      "image": null,
      "recordedAtTs": 1643853501,
      "staticLink": "https://audioboom.com/posts/8024066-episode-296-james-rodney-hicks-part-1",
      "title": "Episode 296: James Rodney Hicks Part 1",
      "waveUrl": "https://images.theabcdn.com/i/w/9090070"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8026167,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8026167-episode-297-james-rodney-hicks-part-2.mp3",
      "downloadURL": null,
      "duration": 6364.22,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>\n<br>We know you have been waiting for the conclusion to this horrific tale, and here it is. James Rodney Hicks destroyed the lives of everyone he came in contact with, but unfortunately he was slipping through the cracks at every turn. Now, armed with decades worth of information and a thirst for justice, Detective Ricker joins forces with a new investigator to take Hicks down once and for all. But not before gruesome details are revealed that would disturb even the most seasoned of detectives.<br><br>\n</div><div>Check out this amazing book on the case: <a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Tragedy-North-Woods-Murders-James-ebook/dp/B00XRCXSCU\">Tragedy In The North Woods by Trudy Irene<br></a><br>\n</div><div>Also, this is an amazing podcast series on this case, including a discussion with Detective Ricker. <a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.murdershetold.com/episodes/1-james-hicks\">Murder She Told</a> (Also this pod is just really great in general!)<br><br>\n</div><div>As always, thank you to our sponsors:<br><br>Curology: Get a free 30-day trial at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://Curology.com/MORBID\">Curology.com/MORBID</a>. Just pay $5 for shipping and handling. <br><br>Daily Harvest: Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://DAILYHARVEST.com/morbid\">DAILYHARVEST.com/morbid</a> to get up to forty dollars off your first box!<br><br>ThirdLove: Right now, you can get 20% off your first order at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://THIRDLOVE.com/MORBID\">THIRDLOVE.com/MORBID</a><br><br>BetterHelp: This podcast is sponsored by BetterHelp and Morbid listeners get 10% off their first month at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BetterHelp.com/morbid\">BetterHelp.com/morbid</a>.<br><br>Jordan Harbinger Show: <a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://podcasts.apple.com/us/podcast/the-jordan-harbinger-show/id1344999619\">https://podcasts.apple.com/us/podcast/the-jordan-harbinger-show/id1344999619</a>\n</div>",
      "image": null,
      "recordedAtTs": 1644024540,
      "staticLink": "https://audioboom.com/posts/8026167-episode-297-james-rodney-hicks-part-2",
      "title": "Episode 297: James Rodney Hicks Part 2",
      "waveUrl": "https://images.theabcdn.com/i/w/9092234"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8064515,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8064515-episode-312-matthew-hoffman-aka-the-leaf-killer-part-2.mp3",
      "downloadURL": null,
      "duration": 6034.73,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>When we left off in part one, Matthew Hoffman had tied Sarah Maynard up so that he could take a nap after brutally killing three of her loved ones. Part two picks up with Matthew clean up the scene while keeping Sarah locked in his cold, dark basement where she was left to sit on a makeshift bed made from, you guessed it....leaves. While Matthew was working on the rest of his plan, like burning down the home, the police were working behind the scenes and luckily able to rescue Sarah. <br><br>Case begins at 11mins 30 seconds because we had a philosophical discussion about not letting toxic shit into your bubble. We understand some people may want to skip! :)<br><br>Check out this amazing book about the case!<br><br>\n</div><div>\n<a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/dp/B00A31UCE0/ref=dp-kindle-redirect?_encoding=UTF8&amp;btkr=1\">The Girl in the Leaves by Robert Scott<br></a><br>\n</div><div>Also, check this out ;)<br><br>\n</div><div>\n<a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://tinyurl.com/thebutcherandthewren\">***US WEIRDOS Pre-Order The Butcher and the Wren: Here *****</a> <br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.waterstones.com/book/the-butcher-and-the-wren/alaina-urquhart/2928377090913\">***UK WEIRDOS Pre-Order a SIGNED copy of The Butcher and the Wren from Waterstones!!***<br></a><br>\n</div><div>\n<a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://fairfieldcf.fcsuite.com/erp/donate/create?funit_id=1199\"><br>Donation link for Tina Rose B. Hermann and Kody Alexander Maynard Healing Hearts Memorial Fund</a> </div><div>\n<br>As always, thank you to our sponsors:<br><br>Betterhelp: Morbid listeners get 10% off their first month at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BetterHelp.com/MORBID\">BetterHelp.com/MORBID</a><br><br>Best Fiends: Download Best Fiends for FREE from the App Store or Google play.<br><br>Liquid IV: Grab Liquid I.V. in bulk nationwide at Costco or you can get 25% off when you go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://LIQUIDIV.COM\">LIQUIDIV.COM</a> and use code MORBID at checkout.<br><br>Canva: Right now, you can get a FREE 45-day extended trial when you use my promo code! Just go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://Canva.me/morbid\">Canva.me/morbid</a> to get your FREE 45-day extended trial.<br><br>Blueland: Right now, you can get 20% off your first order when you go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://Blueland.com/MORBID\">Blueland.com/MORBID</a>\n</div>",
      "image": null,
      "recordedAtTs": 1649620448,
      "staticLink": "https://audioboom.com/posts/8064515-episode-312-matthew-hoffman-aka-the-leaf-killer-part-2",
      "title": "Episode 312: Matthew Hoffman AKA The Leaf Killer Part 2",
      "waveUrl": "https://images.theabcdn.com/i/w/9132732"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8028753,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8028753-episode-298-the-murder-of-abraham-shakespeare.mp3",
      "downloadURL": null,
      "duration": 6219.33,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>In November of 2006 a man named Abraham Shakespeare won the lottery jackpot worth $31 million. Abraham was known as a generous, kind man who would do anything to help his friends, family or children out. Unfortunately a cold-blooded, manipulative woman by the name of Dee Dee Moore would make the acquaintance of Abraham Shakespeare and swindle him out of his millions. Before long, people stopped hearing from Abraham, and some feared the worst. Was he murdered or simply trying to get away from the pressure of it all?<br><br>As always, thank you to our sponsors:<br><br>HelloFresh: Get sixteen free meals, plus three gifts, with code morbid16 at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HELLOFRESH.com/slashmorbid16\">HELLOFRESH.com/slashmorbid16</a><br><br>Noom: Start building better habits today. Sign up for your trial at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://Noom.com/MORBID\">Noom.com/MORBID</a><br><br>Babbel: Right now, when you purchase a 3-month Babbel subscription, you’ll get an additional 3 months for FREE.  Just go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BABBEL.com\">BABBEL.com</a> and use promo code MORBID<br><br>BetterHelp: Morbid listeners get 10% off their first month at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BetterHelp.com/morbid\">BetterHelp.com/morbid</a><br><br>BestFiends: Download Best Fiends FREE today on the App Store or Google Play.</div>",
      "image": null,
      "recordedAtTs": 1644455721,
      "staticLink": "https://audioboom.com/posts/8028753-episode-298-the-murder-of-abraham-shakespeare",
      "title": "Episode 298: The Murder of Abraham Shakespeare",
      "waveUrl": "https://images.theabcdn.com/i/w/9095052"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8066667,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8066667-episode-313-the-unsolved-murder-of-bonny-lee-bakley.mp3",
      "downloadURL": null,
      "duration": 5078.84,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>\n<br>Bonny Lee Bakley’s life is rife with controversy, chaos and just straight up tragedy. She was born into an incredibly toxic environment and seemed to go through life looking for some sense of purpose. She was married multiple times, but her last marriage to actor Robert Blake was the one that added the most controversy. The couple was married only about 5 months when Bonny was murdered on the night of May 4th 2001. Immediately Robert was looked into as a suspect and eventually brought to trial for her murder but the mystery reamins to this day. Who killed Bonny Lee Bakley?</div><div>\n<br>Great book about this case: <a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Blood-Cold-audiobook/dp/B00VN1NP02\">Blood Cold by Dennis McDougal &amp; Mary Murphy</a> <br><br>Also, check this out. I WROTE A BOOK. ;)<br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://tinyurl.com/thebutcherandthewren\">***US WEIRDOS Pre-Order The Butcher and the Wren: Here *****</a> <br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.waterstones.com/book/the-butcher-and-the-wren/alaina-urquhart/2928377090913\">***UK WEIRDOS Pre-Order a SIGNED copy of The Butcher and the Wren from Waterstones!!***<br></a><br>\n</div><div>As always, thank you to our sponsors:<br><br>GoodRX: For simple, smart savings on your prescriptions,<br>check GoodRx. Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://GoodRX.com/Morbid\">GoodRX.com/Morbid</a><br><br>HelloFresh: Get sixteen free meals, plus three gifts, with code morbid16 at HELLO <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://FRESH.com/morbid16\">FRESH.com/morbid16</a><br><br>BetterHelp: Morbid listeners get 10% off their first month at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BetterHelp.com/morbid\">BetterHelp.com/morbid</a><br><br>PrettyLitter: Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://Prettylitter.com\">Prettylitter.com</a> and use code morbid to save twenty percent on your first order.<br><br>Peloton: Visit <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://onepeloton.com\">onepeloton.com</a> to learn more.<br><br>The Jordan Harbinger Show: <a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.jordanharbinger.com/\">https://www.jordanharbinger.com/</a><br><br>\n</div>",
      "image": null,
      "recordedAtTs": 1649887087,
      "staticLink": "https://audioboom.com/posts/8066667-episode-313-the-unsolved-murder-of-bonny-lee-bakley",
      "title": "Episode 313: The Unsolved Murder of Bonny Lee Bakley",
      "waveUrl": "https://images.theabcdn.com/i/w/9135051"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8044557,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8044557-listener-tales-37.mp3",
      "downloadURL": null,
      "duration": 4011.46,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>We’ve made it all the way to the 37th installment of Listener Tales and somehow you guys have done it again!!! You had us cackling with your tales of ankle licking ghosts and life saving Snoop Dogg playlists and shaking in our boots about Skinwalkers ruining camping trips and more! Listener Tales 37 is a treat, enjoy!<br><br>As always, thank you to our sponsors:<br><br>HelloFresh: Get sixteen free meals, plus three gifts, with code morbid16 at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HELLOFRESH.com/morbid16\">HELLOFRESH.com/morbid16</a>.<br><br>SoloStove: Shop now at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://solostove.com\">solostove.com</a> and get up to 30% off fire pits all month long, AND use promo code MORBID at checkout to get an extra $20 off.<br><br>BetterHelp: This podcast is sponsored by BetterHelp and Morbid listeners get 10% off their first<br>month at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BetterHelp.com/morbid\">BetterHelp.com/morbid</a><br><br>Liquid IV: Grab Liquid I.V. in bulk nationwide at Costco or you can get 25% off when you go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://LIQUIDIV.COM\">LIQUIDIV.COM</a> and use code MORBID at checkout.</div>",
      "image": null,
      "recordedAtTs": 1647005760,
      "staticLink": "https://audioboom.com/posts/8044557-listener-tales-37",
      "title": "Listener Tales 37",
      "waveUrl": "https://images.theabcdn.com/i/w/9111746"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8037531,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8037531-episode-301-haunted-lighthouses-volume-1.mp3",
      "downloadURL": null,
      "duration": 4875.52,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>We decided to start a new installment on the show: Haunted Lighthouses! We’re going to try to hit one in every state and in this installment we were able to get to Oregan, Michigan, Maryland, Texas and Georgia. If you have a haunted lighthouse you’d like us to cover send it in to Morbidpodcast@gmail.com with the subject line “Haunted Lighthouse.”<br><br>Some great and fascinating sources used for today's episode:<br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.npr.org/2017/11/30/566950355/the-tempest-at-galveston-we-knew-there-was-a-storm-coming-but-we-had-no-idea\">NPR article mentioned about The Great Galveston Storm</a> <br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Haunted-Lighthouses-Phantom-Shipwrecks-Sinister-ebook/dp/B0040ZN38W/ref=sr_1_1?crid=1KCVBALDMC1PP&amp;keywords=haunted+lighthouses+ray+jones&amp;qid=1645731182&amp;sprefix=haunted+lighthouses+ray+jones%2Caps%2C81&amp;sr=8-1\">Haunted Lighthouses by Ray Jones</a><br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Spookiest-Lighthouses-Discover-Americas-Haunted-ebook/dp/B00EAAQA2S/ref=sr_1_1?crid=12W9J5MMWNMYW&amp;keywords=spookiest+lighthouses&amp;qid=1645731160&amp;sprefix=spookiest+lighthouses%2Caps%2C65&amp;sr=8-1\">Spookiest Lighthouses by Terrance Zepke</a><br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Michigans-Haunted-Lighthouses-America/dp/1467141992/ref=sr_1_1?crid=EK1EEQKG9QGR&amp;keywords=michigan+haunted+lighthouses&amp;qid=1645731193&amp;sprefix=michigan+haunted+lighthouses%2Caps%2C111&amp;sr=8-1\">Michigan's Haunted Lighthouses by Dianna Higgs Stampfler <br></a><br>As always, thank you to our sponsors:<br><br>HelloFresh: Get sixteen free meals, plus three gifts, with code morbid16 at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HELLOFRESH.com/morbid16\">HELLOFRESH.com/morbid16</a><br><br>BetterHelp: This podcast is sponsored by BetterHelp and Morbid listeners get 10% off their first<br>month at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BetterHelp.com/morbid\">BetterHelp.com/morbid</a><br><br>Firstleaf: Join today and you’ll get 6 bottles of wine for $29.95 and free<br>shipping! Just go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://TRYFirstleaf.com/MORBID\">TRYFirstleaf.com/MORBID</a>.<br><br>Native: Get 20% off your first order by going to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://NativeDeo.com/morbid\">NativeDeo.com/morbid</a>, or use promo code morbid at checkout.<br><br>ModernFertility: Right now, Modern Fertility is offering our listeners $20 off the test when you go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://ModernFertility.com/MORBID\">ModernFertility.com/MORBID</a>\n</div>",
      "image": null,
      "recordedAtTs": 1645731319,
      "staticLink": "https://audioboom.com/posts/8037531-episode-301-haunted-lighthouses-volume-1",
      "title": "Episode 301: Haunted Lighthouses Volume 1",
      "waveUrl": "https://images.theabcdn.com/i/w/9104259"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8069925,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8069925-spooky-games-that-will-ruin-your-actual-life-vol-2.mp3",
      "downloadURL": null,
      "duration": 5185.59,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>Spooky Games That Will Ruin Your Actual Life vol.2 is here!!! The first one of these that we put out was literally over 2 years ago so we thought it would be super fun to revisit this topic. Ash goes into the origin story of the iconic sleepover game Light as a Feather Stiff as a Board and  explains The Three Kings Ritual while Alaina brings us the hellacious Black Telephone game, Sara Sarita and The Gathering of 100 Tales. Get ready to be scared to the max and please have some sage on hand, we sure needed it!<br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Dangerous-Games-Play-Lucia-Peters/dp/1452179794/ref=sr_1_1?keywords=dangerous+games+to+play+in+the+dark&amp;qid=1650471263&amp;sprefix=dangerous+games+to+play%2Caps%2C79&amp;sr=8-1\">Dangerous Games to Play in the Dark by Lucia Peters<br></a><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://theghostinmymachine.com\">The Ghost In My Machine</a><br><br>As always, thank you to our sponsors:<br><br>HelloFresh: Get sixteen free meals, plus three gifts, with code morbid16 at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HELLOFRESH.com/morbid16\">HELLOFRESH.com/morbid16</a><br><br>Native: Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://NativeDeo.com/morbid\">NativeDeo.com/morbid</a>, or use promo code morbid at checkout, and get twenty percent off your first order.<br><br>Hunter Douglas: Visit <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HunterDouglas.com/morbid\">HunterDouglas.com/morbid</a> TODAY for your free Style Gets Smarter design guide with fresh takes, creative ideas and smart solutions for dressing your windows!<br><br>Rothys: Get $20 off your first purchase today at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://rothys.com/MORBID\">rothys.com/MORBID</a><br><br>Modern Fertility: Get $20 off your fertility test when you go to Modern Fertility dot com slash MORBID<br><br>The Jordan Harbinger show: <a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.jordanharbinger.com/podcasts/\">https://www.jordanharbinger.com/podcasts/</a>\n</div>",
      "image": null,
      "recordedAtTs": 1650471338,
      "staticLink": "https://audioboom.com/posts/8069925-spooky-games-that-will-ruin-your-actual-life-vol-2",
      "title": "Spooky Games That Will Ruin Your Actual Life Vol.2",
      "waveUrl": "https://images.theabcdn.com/i/w/9138554"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8062294,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8062294-episode-311-matthew-hoffman-aka-the-leaf-killer.mp3",
      "downloadURL": null,
      "duration": 5626.64,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>Matthew John Hoffman was a strange guy. He was in a constant flux of being a quiet, yet unassuming guy to then having bouts of strange and off-putting behavior. It was his love of trees that gave him comfort and seemed to keep him settled at times, but on November 9, 2010 he broke into a quiet home in Apple Valley, Ohio, brutally taking the lives of Tina Hermann, her 11 year old son Kody and her best friend Stephanie Sprang, before leaving with 13 year old Sarah Maynard in his clutches. <br><br>Soon, Hoffman's obsession with trees would become the defining piece of this killer's pathology. In Part 1, we discuss his puzzling history, the lives of Tina, Kody and Stephanie, and the house of horrors he brought Sarah back to. <br><br>\n</div><div>Check out this amazing book about the case!<br><br>\n</div><div>\n<a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/dp/B00A31UCE0/ref=dp-kindle-redirect?_encoding=UTF8&amp;btkr=1\">The Girl in the Leaves by Robert Scott</a> <br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://tinyurl.com/thebutcherandthewren\">***US WEIRDOS Pre-Order The Butcher and the Wren: Here *****</a> <br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.waterstones.com/book/the-butcher-and-the-wren/alaina-urquhart/2928377090913\">***UK WEIRDOS Pre-Order a SIGNED copy of The Butcher and the Wren from Waterstones!!***</a><br><br>\n</div><div>HelloFresh: Get sixteen free meals, plus three gifts, with code morbid16 at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HELLOFRESH.com/morbid16\">HELLOFRESH.com/morbid16</a><br><br>Warby Parker: Try 5 pairs of glasses at home for free at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://warbyparker.com/morbid\">warbyparker.com/morbid</a><br><br>Prose: Take your FREE in-depth hair consultation and get 15% off your first<br>order today by going to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://Prose.com/morbid\">Prose.com/morbid</a><br><br>Solo Stove: Just go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://solostove.com\">solostove.com</a> and remember, you get $20 off when you use promo code MORBID!<br><br>CareOf: For 50% off your first Care/of order of $40 or more, go to TakeCareOf .comand enter code morbid50<br><br>\n</div><div><br></div>",
      "image": null,
      "recordedAtTs": 1649268229,
      "staticLink": "https://audioboom.com/posts/8062294-episode-311-matthew-hoffman-aka-the-leaf-killer",
      "title": "Episode 311: Matthew Hoffman AKA The Leaf Killer",
      "waveUrl": "https://images.theabcdn.com/i/w/9130253"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8076509,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8076509-the-kreischer-mansion.mp3",
      "downloadURL": null,
      "duration": 5384.29,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>The Kreischer mansion on Staten Island is the only property around that belonged to the famous Kreischer family, who made their living producing firebricks in the 1800’s. The property, which sits at 4500 Arthur Kill Road, has long been rumored to be haunted as fuck. In the episode we’ll go over all of the hauntings throughout the years, speak about a murder that unfortunatley took place on the property and what the future holds for this beautifully macabre building. <br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.miamighostchronicles.com/kreischer-mansion.html\">*a great source for more info!!*<br></a><br>As always, thank you to our sponsors:<br><br>Scribd: Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://try.scribd.com/MATCP\">try.scribd.com/MATCP</a> to get your first two months for less than $1<br><br>Skylight Frame: To get $10 off your purchase of a Skylight Frame just go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://SkylightFrame.com\">SkylightFrame.com</a> and enter code MATCP<br><br>BetterHelp: Morbid listeners get 10% off their first month at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BetterHelp.com/morbid\">BetterHelp.com/morbid</a><br><br>Care of: For 50% off your first Care/of order, go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://TakeCareOf.com\">TakeCareOf.com</a> and enter code morbid50.<br><br>The Jordan Harbinger Show: <a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.jordanharbinger.com/podcasts/\">https://www.jordanharbinger.com/podcasts/</a>\n</div>",
      "image": null,
      "recordedAtTs": 1651525171,
      "staticLink": "https://audioboom.com/posts/8076509-the-kreischer-mansion",
      "title": "The Kreischer Mansion",
      "waveUrl": "https://images.theabcdn.com/i/w/9145597"
    },
    {
      "author": "Morbid: A True Crime Podcast",
      "clipId": 8010900,
      "clipURLPriorToLoading": "https://audioboom.com/posts/8010900-episode-290-the-tragic-murder-of-phil-hartman.mp3",
      "downloadURL": null,
      "duration": 5514.54,
      "embedDisabled": false,
      "seasonNumber": null,
      "episodeNumber": null,
      "formattedDescription": "<div>This is the story of Phil Hartman and the episode is a little different than some we’ve done in the past. We all know Ash loves an “Old Hollywood” kind of case, this one while not very old at all fits under the umbrella. Phil Hartman was one of the most beloved comedians of all times, often referred to as, “The Man of 1000 voices.” When you dive into his life as a whole you find all kinds of hidden gems, like the fact that Phil had a run in with Jimi Hendrix, and so many more little anecdotes like that! Unfortunately, Phil was taken from this world far too soon and in such a horrific way. <br><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/You-Might-Remember-Me-Hartman-ebook/dp/B00IQOJE40\">You Might Remember Me by Mike Thomas<br></a><br><a target=\"_blank\" rel=\"nofollow noopener\" href=\"https://www.amazon.com/Live-New-York-Complete-Uncensored/dp/031629506X\">Live from New York: The Complete Uncensored History of Saturday night Live as told by its stars writers and guests (James Andrew Miller and Tom Shales)<br></a><br>As always, thank you to our sponsors:<br><br>HelloFresh: Get sixteen free meals, plus three gifts, with code morbid16 at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://HELLOFRESH.com/morbid16\">HELLOFRESH.com/morbid16</a><br><br>BetterHelp: This podcast is sponsored by BetterHelp and Morbid listeners get 10% off their first month at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://BetterHelp.com/morbid\">BetterHelp.com/morbid</a><br><br>Rothy’s: New customers get $20 off your first purchase at <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://rothys.com/MORBID\">rothys.com/MORBID</a><br><br>Native: Go to <a target=\"_blank\" rel=\"nofollow noopener\" href=\"http://NativeDeo.com/morbid\">NativeDeo.com/morbid</a>, or use promo code morbid at checkout, and get twenty percent off your first order.</div>",
      "image": null,
      "recordedAtTs": 1641918711,
      "staticLink": "https://audioboom.com/posts/8010900-episode-290-the-tragic-murder-of-phil-hartman",
      "title": "Episode 290: The Tragic Murder of Phil Hartman",
      "waveUrl": "https://images.theabcdn.com/i/w/9075496"
    }
  ]
}


module.exports.rawData = rawData;
