let rawData = [
  {
    "name": "Gita For Daily Living by Neil Bhatt",
    "url": "https://mcdn.podbean.com/mf/web/2fmxnt/Gita_Ch_5_V_22_23_24.mp3",
    "homepage": "https://www.radioindia.in/podcasts/gita-for-daily-living",
    "favicon": "https://static.mytuner.mobi/media/podcasts/091/gita-for-daily-living.jpg",
    "tags": "gita, india,",
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Saregama Carvaan Classic Retro Music by Saregama India Ltd",
    "url": "http://saregamawsa.bc.cdn.bitgravity.com/weekend_radio/audio/2019_12_CCRS_iTunes_Hindi_Week_4_Trio-Hema_Malini-Lata_Mangeshkar-Laxmikant_Pyarelal_Spl.mp3",
    "homepage": "https://www.radioindia.in/podcasts/saregama-weekend-classic-retro-music",
    "favicon": "https://is4-ssl.mzstatic.com/image/thumb/Podcasts125/v4/9f/2e/53/9f2e539f-1cdd-a247-868d-5fbd2108cfda/mza_9262458932532537564.jpg/100x100bb.jpg",
    "tags": "india,",
    "description": `A unique digital radio show which plays retro Bollywood songs and stories from the era of 60s, 70s, 80s, 90s and early 2000s. Enjoy songs and stories that became a part of popular stars like Madhubala, Amitabh Bachchan, Rajesh Khanna, Dev Anand, Dharmendra, Raj Kapoor, Jitendra, Sharlima Tagore, Parveen Babi, Waheeda Rahman and more. Walk through the journey of legends like Lata Mangeshkar, Mohd Rafi, R.D. Burman, Asha Bhosle and more. Carvaan Classic is the only place where you will hear stories like "Dum Maro Dum song was rejected by Dev Anand, what changed his mind ?" or "Which super star helped Kishore Kumar come out of his depression?" or "What was R.D. Burman’s reply when Asha Bhosle complained to him that he always lets Lata Mangeshkar sing his best composed songs ?" and many more.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Crazy For Kishore by Radio Nasha - HT smartcast",
    "url": "https://play.hubhopper.com/4ba4be4b82ce0a19a0485cc2228e1b03.mp3?s=rss-feed",
    "homepage": "https://www.radioindia.in/podcasts/crazy-for-kishore",
    "favicon": "https://static.mytuner.mobi/media/podcasts/226/crazy-for-kishore.jpg",
    "tags": "kishore, classic music, Radio Nasha - HT smartcast",
    "description": `In this podcast, listen to a retro cool show by Amit Kumar and Sumit Kumar, sons of legendary Kishore Kumar. Tune in to listen to pieces revolving around the madness and untold stories of Kishore Kumar. This is a Radio Nasha production, brought to you by HT smartcast.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Sadhguru by Sadhguru Official",
    "url": "https://play.hubhopper.com/e706e201fc554d5166adfbff45aaf920.mp3?s=rss-feed&v=d532bc57eda3",
    "homepage": "https://www.radioindia.in/podcasts/crazy-for-kishore",
    "favicon": "https://static.mytuner.mobi/media/podcasts/569/sadhgurus-podcast.jpg",
    "tags": "Sadhguru Official, Religion & Spirituality,",
    "description": `Sadhguru, founder of Isha Foundation is a yogi, mystic and spiritual master with a difference. An arresting blend of profundity and pragmatism, his life and work serve as a reminder that inner sciences are not esoteric philosophies from an outdated past, but a contemporary science vitally relevant to our times.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta",
    "url": "https://audioboom.com/posts/5554578.mp3?modified=1575064083&source=rss&stitched=1https://audioboom.com/posts/5554578.mp3?modified=1575064083&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": ", Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Pratham Adhya",
    "url": "https://audioboom.com/posts/5554576.mp3?modified=1575054713&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": ", Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta second Adhya",
    "url": "https://audioboom.com/posts/5554571.mp3?modified=1575069745&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Third Adhya",
    "url": "https://audioboom.com/posts/5554569.mp3?modified=1575047396&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Fourth Adhya",
    "url": "https://audioboom.com/posts/5554566.mp3?modified=1575053324&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Fifth Adhya",
    "url": "https://audioboom.com/posts/5554540.mp3?modified=1575039960&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Sixth Adhya",
    "url": "https://audioboom.com/posts/5554539.mp3?modified=1575063038&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Seventh Adhya",
    "url": "https://audioboom.com/posts/5554537.mp3?modified=1575061357&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Eigth Adhya",
    "url": "https://audioboom.com/posts/5554536.mp3?modified=1575058279&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Nineth Adhya",
    "url": "https://audioboom.com/posts/5554534.mp3?modified=1575042996&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Tenth Adhya",
    "url": "https://audioboom.com/posts/5554531.mp3?modified=1575056812&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Eleventh Adhya",
    "url": "https://audioboom.com/posts/5554528.mp3?modified=1575069392&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Twelveth Adhya",
    "url": "https://audioboom.com/posts/5554525.mp3?modified=1575065824&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Thirteen Adhya",
    "url": "https://audioboom.com/posts/5554523.mp3?modified=1575042342&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Fourteenth Adhya",
    "url": "https://audioboom.com/posts/5554522.mp3?modified=1575063038&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Fifteenth Adhya",
    "url": "https://audioboom.com/posts/5554519.mp3?modified=1575059949&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Sixteenth Adhya",
    "url": "https://audioboom.com/posts/5554503.mp3?modified=1575051895&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Seventeenth Adhya",
    "url": "https://audioboom.com/posts/5554499.mp3?modified=1575052608&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Eighteenth Adhya",
    "url": "https://audioboom.com/posts/5554497.mp3?modified=1575051522&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "Bhagavad Gita Hindi by Yatharth Geeta Nineteenth Adhya",
    "url": "https://audioboom.com/posts/5554493.mp3?modified=1575048056&source=rss&stitched=1",
    "homepage": "https://www.radioindia.in/podcasts/bhagavad-gita-hindi",
    "favicon": "https://static.mytuner.mobi/media/podcasts/334/bhagavad-gita-hindi.jpg",
    "tags": "gita, Religion & Spirituality, Religion & Spirituality",
    "description": `This podcast covers Gita in its True perspective. 5200 years long interval Srimad Bhagavad Gita in its authentic and everlasting exposition : The Science of Religion for Mankind : Yatharth Geeta by Swami Adgadanand.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  //red fm baua start here
  {
    "name": "1092 - RED FMBAUAA: RJ RAUNAC AND BAUAA  MAJE ON ALAS ",
    "date": "Mon, 25 Apr 2022 ",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/9770e316-ad96-4fdb-9a5b-ae82006dbfe9/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1091 - REDFM BAUAA: RJ RAUNAC AND BAUAA MAJE ON DHOODH PANEER ",
    "date": "Fri, 22 Apr 2022 ",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/bbb24346-77f7-4e5b-9545-ae7f006f0403/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1090 - RED FM BAUAA :- RJ RAUNAC AND BAUAA MAJE ON MUTHI MEIN KYA HAI ",
    "date": "Tue, 08 Feb 2022",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/d8638f01-5fc4-40c8-a9d4-ae3600b7d898/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1089 - RED FM BAUAA :- RJ RAUNAC AND BAUAA MAJE ON ENGLISH KE WORDS KO HINDI MEIN TRANSLATE ",
    "date": "Tue, 01 Feb 2022",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/46ddcbd4-e33e-47fc-9cf6-ae2f00979a97/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1088 - RED FM BAUAA :- RJ RAUNAC MAJE ON TEACHER KE PASS JYADA DIMAG HOTA HAI ",
    "date": "Mon, 31 Jan 2022",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/c9f9d102-c29e-4c2a-8c68-ae2e005f171a/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1087 - RED FM BAUAA:- RJ RAUNAC AND BAUAA MAJE ON KYUN TEACHER BEST HOTEY HAI ",
    "date": "Fri, 14 Jan 2022",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/8ebdfd4e-fc89-4d81-b545-ae1d0044c1c5/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1086 - RJ RAUNAC AND BAUAA MAJE ON MUHAVRON KI MARAMMAT ",
    "date": "Wed, 05 Jan 2022",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/20a52c27-7415-4713-a109-ae140082fadc/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1085 - RED FM BAUAA :- RJ RAUNAC AND BAUAA MAJE ON MUH PE ACCHA BANN NA SEEKHO ",
    "date": "Tue, 21 Dec 2021",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/6e6dc228-49a7-434d-a209-ae0500cbda88/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1084 - RJ RAUNAC AND BAUAA MAJE ON DOCTOR KI SHAADI FINAL ",
    "date": "Fri, 17 Dec 2021",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/3da16a11-81b6-4f49-b2fa-ae010067266b/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1083 - RED FM BAUAA :- KYA HAI DUNIYA KE NIYAM YE SUNO BAUAA NE KAISE MAJE LIYE ",
    "date": "Thu, 02 Dec 2021",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/f1be0ea8-2d6d-407c-bbfe-adf2007a925e/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1082 - RED FM BAUAA :- RJ RAUNAC AND BAUAA MAJE ON THAND WAALI SHAYRI ",
    "date": "Fri, 26 Nov 2021",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/81508d8d-4b78-4f75-ab45-adec00652d4d/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1081 - RED FM BAUAA :- RJ RAUNAC AND BAUAA MAJE ON KHALI TIME PASS ",
    "date": "Mon, 15 Nov 2021",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/1ce5c6ad-d2d1-47ed-aa5d-ade100bfe0e8/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1080 - RED FM BAUAA :- RJ RAUNAC AND BAUAA MAJE ON OPEN LETTER TO TEAM INDIA ",
    "date": "Tue, 09 Nov 2021",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/f5451a5d-38a8-4ca7-a3f0-addb005e1b07/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
    "name": "1079 - RED FM BAUAA :- RJ RAUNAC AND BAUAA MAJE ON POST DIWALI ",
    "date": "Fri, 05 Nov 2021",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/fa93eeb8-b8bc-42c0-a6da-add700589bd1/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
  {
  "name": "1078 - RED FM BAUAA :- RJ RAUNAC AND BAUAA MAJE ON DIWALI FESTIVAL MSG  ",
  "date": "Thu, 04 Nov 2021",
  "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/67364951-8640-484f-b734-add6003c5e5f/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
  "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
  "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
  "tags": "comedy",
  "description": `World famous in Delhi, the kid who pranks all.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
  {
  "name": "1079 - RED FM BAUAA :- RJ RAUNAC AND BAUAA MAJE ON POST DIWALI ",
  "date": "Fri, 05 Nov 2021",
  "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/fa93eeb8-b8bc-42c0-a6da-add700589bd1/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
  "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
  "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
  "tags": "comedy",
  "description": `World famous in Delhi, the kid who pranks all.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
  },
  {
  "name": "1077 - RED FM BAUAA :- BUKHAR MEIN SIR PE HE PAANI KA KAPDA KYUN RAKHTE HAI YE SUNO...  ",
  "date": "Thu, 28 Oct 2021",
  "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/bbf53976-7d75-4869-975c-adcf005acef7/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
  "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
  "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
  "tags": "comedy",
  "description": `World famous in Delhi, the kid who pranks all.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
  },
  {
  "name": "1076 - RED FM BAUAA :- BAUAA NE LAGYAA PHIR PAKISTAN CALL AUR LIYE MAJE ",
  "date": "Mon, 25 Oct 2021",
  "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/85e2c4a9-19cb-4211-9176-adcc007270cc/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
  "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
  "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
  "tags": "comedy",
  "description": `World famous in Delhi, the kid who pranks all.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
  },
  {
  "name": "1075 - RED FM BAUAA :- BAUAA KE AJEEB SAWAAL SUNE KYA AAPNE ",
  "date": "Mon, 18 Oct 2021",
  "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/38f2fb2c-71d6-4f70-98ca-adc500bf8e08/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
  "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
  "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
  "tags": "comedy",
  "description": `World famous in Delhi, the kid who pranks all.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
  },
  {
  "name": "1074 - RED FM BAUAA :- RJ RAUNAC AND BAUAA MAJO ON AADHI BAAT AUR AADHA GYAN DONO KHATARNAAK ",
  "date": "Thu, 14 Oct 2021",
  "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/2fe7620d-c5f3-4bb9-b868-adc100a5ad07/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
  "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
  "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
  "tags": "comedy",
  "description": `World famous in Delhi, the kid who pranks all.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
  },
  {
  "name": "1073 - RED FM BAUAA :- BAUAA NE KYA KAHA KI THEEK SE NAHI HO PAA RAHI ",
  "date": "Thu, 07 Oct 2021",
  "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/cfcfa5b4-bf87-462e-88ae-adba0063d34c/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
  "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
  "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
  "tags": "comedy",
  "description": `World famous in Delhi, the kid who pranks all.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
  },
  {
  "name": "1072 - RED FM BAUAA :- BAUAA NE KI GHUMA FIRAKE BAAT YE SUNO... ",
  "date": "Fri, 01 Oct 2021",
  "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/57e48781-b169-4d65-95f3-adb401343649/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
  "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
  "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
  "tags": "comedy",
  "description": `World famous in Delhi, the kid who pranks all.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
  },
  {
  "name": "1071 - RED FM :- RJ RAUNAC AND BAUAA MAJE ON TRAVEL ",
  "date": "Wed, 29 Sep 2021",
  "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/1e814051-d77a-4db1-bcf7-adb2003630f7/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
  "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
  "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
  "tags": "comedy",
  "description": `World famous in Delhi, the kid who pranks all.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
  },
  {"name": "1070 - RED FM BAUAA :- RJ RAUNAC AND BAUAA MAJE ON T-20 MUMBAI TEAM ",
  "date": "Tue, 28 Sep 2021",
  "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/8a0f0187-dc20-43c1-9b65-adb10037350f/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
  "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
  "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
  "tags": "comedy",
  "description": `World famous in Delhi, the kid who pranks all.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
  },
  {
    "name": "1069 - RED FM BAUAA :- RJ RAUNAC AND BAUAA MAJE ON VIRAT KOHLI ",
    "date": "Tue, 21 Sep 2021",
    "url": "https://traffic.omny.fm/d/clips/8ce708b9-c3c2-4eaa-a27d-ac0f007c53c5/232a6ee0-f0fb-4a77-a1cd-ac22009d88c7/5c932fca-f5bd-4930-80be-adaa005d6f83/audio.mp3?utm_source=Podcast&in_playlist=8c8aa2ff-faca-4553-a635-ac22009d88d0",
    "homepage": "https://www.radioindia.in/podcasts/red-fm-bauaa",
    "favicon": "https://static.mytuner.mobi/media/podcasts/240/red-fm-bauaa-red-fm.jpg",
    "tags": "comedy",
    "description": `World famous in Delhi, the kid who pranks all.`,
    "country": "India",
    "countrycode": "IN",
    "state": "New Delhi",
    "language": "hindi",
    "languagecodes": "hi",
  },
//red fm baua end here
{
  "name": "Ishq FM",
  "date": "",
  "url": "https://drive.uber.radio/uber/bollywoodlove/icecast.audio",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/ishq",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/logo.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Ishq FM is an online radio station from Mumbai (India). Broadcasting was opened in 2016. Listen to Bollywood and Love Songs content in good quality in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio City Hindi",
  "date": "",
  "url": "https://stream.zeno.fm/pxc55r5uyc9uv",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/city-hindi",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/City-Hindi.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Radio City Hindi is an internet radio station on the Planet Radio City. The station is targeted for Hindi speakers. The radio daily broadcasts entertainment and information programs for its attentive listeners. For you, the best presenters broadcast a lot of Bollywood songs. Daily relevant news in the native language is also to your attention.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Meethi mirchi",
  "date": "",
  "url": "https://mirchiplaylive.akamaized.net/hls/live/2036929/MUM/MEETHI64kbps.m3u8",
  "type": "m3u8",
  "homepage": "https://onlineradiofm.in/stations/meethi-mirchi",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/meetmirchi.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `
        Meethi Mirchi is an online radio station broadcasting from Mumbai to Hindi that belongs to Radio Mirchi. Every day, the station plays melodic songs for its beloved listeners. Listen to hits from Bollywood, as well as many interesting programs, such as Bollywood Safari with Sunny and Jussay With Jassi.
  `,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Hungama 90s Once Again",
  "date": "",
  "url": "https://securestreams8.autopo.st:3003/1",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/ishq",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/Hungama90sOnceAgain.jpg",
  "tags": "Hindi love, bollywood, love songs, old songs",
  "description": `
    Radio Hungama 90s Once Again is an online station from Mumbai (India). Broadcasting was opened in 2009. Listen to old songs and Bollywood content in quality 96 Kbps in free live streaming.
  `,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Hungama Evergreen Bollywood",
  "date": "",
  "url": "https://radioindia.net/radio/hungama_evergreen_bollywood/icecast.audio",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/hungama-evergreen-bollywood",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/logo.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": "Radio Hungama Evergreen Bollywood is an online station from Mumbai (India). Broadcasting was opened in 2009. Listen to old songs and Bollywood content in quality 96 Kbps in free live streaming.",
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Non Stop Hindi Radio",
  "date": "",
  "url": "https://vobook.ru:/http://198.178.123.14:8216/;",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/non-stop-hindi",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/nonstophindi.png",
  "tags": "Hindi love, bollywood, love songs, non stop",
  "description": `Non Stop Hindi Radio is an online station from (India). Listen to Bollywood content in quality 64 Kbps in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Hits Of Bollywood",
  "date": "",
  "url": "https://node-01.zeno.fm/60ef4p33vxquv?rj-ttl=5&rj-token=AAABbGBHGlcdu87e_YRpIHrxfAnsfcqIAsypLZXICYMhp0FFSpBJjw",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/hits-of-bollywood",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/hitsofbollywood.png",
  "tags": "Hindi love, bollywood, love songs, classic",
  "description": "Radio Hits Of Bollywood was founded specifically for the Indian community around the world. Only popular new and old hindi songs are played at this station. Live streaming of HOB at 128 kbps 24/7 and enjoy the best music from India.",
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Kishore Kumar Radio",
  "date": "",
  "url": "https://node-11.zeno.fm/0ghtfp8ztm0uv.aac",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/city-kishore-kumar",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/kishhorekumar.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Kishore Kumar - this is an Internet station that will introduce you to the work of a famous Indian singer, composer and songwriter - Kishore Kumar. He is considered one of the most popular singers of the Indian film industry. Energetic melodies, romantic songs for dancing will create a good mood for you all day. Listen live to the best tunes in good quality!`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Hungama Bollywood Dil Se",
  "date": "",
  "url": "https://securestreams8.autopo.st:3001/1",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/hungama-bollywood-dil-se",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/bollywooddilse.jpg",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Radio Hungama Bollywood Dil Se is an online station from Mumbai (India). Broadcasting was opened in 2009. Listen to Bollywood content in quality 96 Kbps in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Hungama Hot now Bollywood",
  "date": "",
  "url": "https://securestreams8.autopo.st:3027/1",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/hungama-hot-now-bollywood",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/hot-now-bollywood.jpg",
  "tags": "new Hindi, bollywood, love songs, hindi rock",
  "description": `Radio Hungama Hot now Bollywood is an online station from Mumbai (India). Broadcasting was opened in 2009. Listen to Bollywood content in quality 96 Kbps in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Hungama - Dance Masti International",
  "date": "",
  "url": "https://radioindia.net/radio/hungamamasti/icecast.audio",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/hungama-dance-masti-international",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/Hungama-Dance-Masti-International.jpg",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Radio Hungama - Dance Masti International is an online station from Mumbai (India). Broadcasting was opened in 2009. Listen to dance content in quality 96 Kbps in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Hungama Best of Ghazals",
  "date": "",
  "url": "https://radioindia.net/radio/hungamaghazal/icecast.audio",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/hungama-mehfil",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/Hungama-best-of-glazal.jpg",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Radio Hungama Best of Ghazals is an online station from Mumbai (India). Broadcasting was opened in 2009. Listen to old songs and classic content in quality 96 Kbps in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Retro Bollywood",
  "date": "",
  "url": "https://stream.zeno.fm/g372rxef798uv",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/retro-bollywood",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/Retro-Bollywood444.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Listen to your evergreen old bollywood music 24x7. This radio is for those who are looking for 80's, 90's and 2000 movie songs. Only selected songs are being played hear which are heart touching and will make you tune this radio station again and again.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Bollywood Radio and Beyond",
  "date": "",
  "url": "https://s6.yesstreaming.net/proxy/john1237?mp=/live",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/bollywood-and-beyond",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/bollywood-beyond11.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Listen to Bollywood Radio and Beyond online in quality 128 Kbps. Broadcasting was opened in Greensboro (USA) in 2010. At this station, for you, plays the best new and old indian classic hindi songs and popular english hits in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio XL",
  "date": "",
  "url": "https://radioindia.net/radio/xl/icecast.audio",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/hungama-mehfil",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/radioxz.png",
  "tags": "Hindi love, bollywood, love songs, english",
  "description": `Radio XL is an online station from Birmingham (United Kingdom). Listen to Bollywood and classic content in quality 64kbps in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Awaz FM",
  "date": "",
  "url": "https://radioindia.net/radio/awazfm/icecast.audio",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/hungama-mehfil",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/awazfmlogopink-wht-large_webaddr-blk.jpg",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Radio Awaz FM is an online station from Glasgow (United Kingdom). Broadcasting was opened in 2001. Listen to Bollywood content in quality 32 Kbps in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Gilli 106.5 FM",
  "date": "",
  "url": "https://livessl.rcast.net/stream/66462.mp3",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/gilli-106.5-fm",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/radiogilli1.png",
  "tags": "Hindi love, bollywood, love songs, tamil song",
  "description": `Radio Gilli 106.5 FM is an online station from Um Al Quweim (United Arab Emirates). Broadcasting was opened in 2017. Listen to Bollywood content in quality 192 Kbps in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "Tamil",
  "languagecodes": "hi",
},
{
  "name": "KSJO Radio Bolly 92.3 FM",
  "date": "",
  "url": "https://radioindia.net/radio/bolly923/icecast.audio",
  "type": "audio/mpeg",
  "homepage": "https://bolly923fm.com/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/bolly923fm.jpg",
  "tags": "Hindi love, bollywood, love songs",
  "description": `KSJO Radio Bolly 92.3 FM is an online station from San Jose (USA). Listen to Bollywood content in quality 64 Kbps in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Bollywood Punjabi Radio",
  "date": "",
  "url": "http://stream.zeno.fm/1k0y9f0cm0quv",
  "type": "audio/mpeg",
  "homepage": "https://bollywoodpunjabiradio.blogspot.com/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/bollywood-punjabi-radio-logo.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Bollywood Punjabi Radio is an online station from (India). Listen to Bollywood content in good quality in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio City Love Guru",
  "date": "",
  "url": "https://stream.zeno.fm/v43eksh02s8uv",
  "type": "audio/mpeg",
  "homepage": "http://www.radiocity.in",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/loveguru.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Listen to Radio City Love Guru online in quality 64 Kbps. Broadcasting was opened in Pune (India) in 1985. At this station, for you, plays the best relax, bollywood, the Love Songs content in free live streaming. Love Guru - is unknown by face & identity - can suggest some solutions to your love problems & wishes everyone to have problem free - love life`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Mohammed Rafi Radio",
  "date": "",
  "url": "https://node-19.zeno.fm/2xx62x8ztm0uv.aac",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/city-mohammed-rafi",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/rafi.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Radio Mohammed Rafi – this station is dedicated to the Indian singer and composer - Mohammed Rafi. He is known for being able to adapt his voice to the desired song. In his work, there are romantic, patriotic, and peppy tunes. Rafi was recognized as the best voice in the movie in Hindi. Listen daily, in good quality, to his best works that will create your mood.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio City Dance",
  "date": "",
  "url": "https://stream.zeno.fm/ugqasdpvyc9uv",
  "type": "audio/mpeg",
  "homepage": "http://www.radiocity.in",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/PlanetRadioCity-Dance.jpg",
  "tags": "Hindi love, bollywood, love songs, dance",
  "description": `Radio City Dance is a station that broadcasts the most beautiful songs for dancing. On this channel, you will listen to the coolest tracks from Hardwell, Skrillex, Martin Garrix, Tiesto, and many others. Listen live to famous tracks, rhythmic and funny ones, in good quality. Many entertainment programs for dear listeners. The station works every day, all week!`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio City Ghazal",
  "date": "",
  "url": "https://stream.zeno.fm/bbczdmqd8f0uv",
  "type": "audio/mpeg",
  "homepage": "https://onlineradiofm.in/stations/hungama-mehfil",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/City-Ghazal.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Radio City Ghazal – on this channel you will get acquainted with a special genre of love poem or ode - Ghazal. It is a short poem consisting of rhyming couplets. On this channel, you will hear many stories about love and separation, in several languages. Besides, there are famous folk melodies and songs of past decades! Listen live in good quality!`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Rabindra Sangeet Radio",
  "date": "",
  "url": "blob:https://onlineradiofm.in/a5d44242-f982-4752-b174-bc2497790e55",
  "type": "audio/mpeg",
  "homepage": "https://gaana.com/radio/mirchiplay-rabindra-sangeet",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/City-Ghazal.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Rabindra Sangeet Radio - this is an Internet station dedicated to singer and composer Rabindra Sangeet. He composed several thousand songs, and became very popular. The songs have distinctive characteristics of romanticism and poetry. He combined Hindustani classical music, Carnatic Classical, Western tunes and the inherent Folk style. His best works are featured by host Mirchi Sree, in good quality, all week.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio City 91.1 FM",
  "date": "",
  "url": "https://prclive1.listenon.in/",
  "type": "audio/mpeg",
  "homepage": "https://www.radiocity.in",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/radiocity9911.jpg",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Radio City 91.1 is the first India's national private fm radio stations. It broadcasts in most of 40 cities on 91.1 FM and has 69 millions radio listeners. Radio Network was founded 3 July 2001 in Bangalore. Listen to the mix of Hindi and Regional music on the air 24/7.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Lata Mangeshkar",
  "date": "",
  "url": "https://node-04.zeno.fm/87xam8pf7tzuv.aac?rj-ttl=5&rj-tok=AAABdd9L970AyueqcJw1yBsdCA",
  "type": "audio/mpeg",
  "homepage": "https://zeno.fm/lata-mangeshkar/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/RadioCity-LataMangeshkarRadio2222.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Radio Lata Mangeshkar is dedicated to an Indian singer and music director. She was born on September 28, 1929. Her works are known in regional Indian languages and foreign languages, though primarily in Marathi, Hindi, Bengali and Assamese. For her work, she received many awards and prizes. She is one of the most talented people in India. Listen live to, melodic songs for a good mood! Stay with us!`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Taj",
  "date": "",
  "url": "https://radioindia.net/radio/taj/icecast.audio",
  "type": "audio/mpeg",
  "homepage": "https://radiotaj.com/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/Screenshot_7.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Radio Taj is an online station from (Spain). Listen to Bollywood content in quality 64 Kbps in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Hum 106.1 FM",
  "date": "",
  "url": "https://ice10.securenetsystems.net/HUMFM?playSessionID=ECACF786-A4F2-6C95-7BD7DCE1A730EE1A",
  "type": "audio/mpeg",
  "homepage": "http://www.humfmradio.com",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/City-Ghazal.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": `Radio Hum 106.1 FM is an online station from Houston (USA). Listen to news and Bollywood content in quality 32 Kbps in free live streaming.`,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Bombay Hott Radio",
  "date": "",
  "url": "https://50stations.com/proxy/newbombay?mp=/stream",
  "type": "audio/mpeg",
  "homepage": "https://www.bombayhottradio.com/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/City-Ghazal.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Bombay Hott Radio is an online station from Mumbai (India). Broadcasting was opened in 2012. Listen to Bollywood and rock content in quality 128 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio rhythm AM",
  "date": "",
  "url": "https://radioindia.net/radio/rhyte/icecast.audio",
  "type": "audio/mpeg",
  "homepage": "http://radiorhythm.com.au/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/Screenshot_6.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Radio rhythm AM is an online station from Brisbane (Australia). Listen to Bollywood content in quality 53 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Abee radio",
  "date": "",
  "url": "https://abee.radioca.st/stream",
  "type": "audio/mpeg",
  "homepage": "http://www.humfmradio.com",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/abeeradio.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Abee radio is an online station from Los Angels (USA). Listen to indian music and Bollywood content in quality 128 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Hum 106.1 FM",
  "date": "",
  "url": "https://ice10.securenetsystems.net/HUMFM?playSessionID=ECACF786-A4F2-6C95-7BD7DCE1A730EE1A",
  "type": "audio/mpeg",
  "homepage": "http://www.humfmradio.com",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/City-Ghazal.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": ``,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Hum 106.1 FM",
  "date": "",
  "url": "https://ice10.securenetsystems.net/HUMFM?playSessionID=ECACF786-A4F2-6C95-7BD7DCE1A730EE1A",
  "type": "audio/mpeg",
  "homepage": "http://www.humfmradio.com",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/City-Ghazal.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": ``,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Hum 106.1 FM",
  "date": "",
  "url": "https://ice10.securenetsystems.net/HUMFM?playSessionID=ECACF786-A4F2-6C95-7BD7DCE1A730EE1A",
  "type": "audio/mpeg",
  "homepage": "http://www.humfmradio.com",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/City-Ghazal.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": ``,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Australian Indian Radio",
  "date": "",
  "url": "https://radioindia.net/radio/australianradio/icecast.audio",
  "type": "audio/mpeg",
  "homepage": "http://indianradio.net.au/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/AIR-logo.jpg",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Australian Indian Radio is an online station from Brisbane (Australia). Listen to indian music and old songs content in quality 64 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Tune India Radio Bollywood",
  "date": "",
  "url": "https://s2.radio.co/se5e166e2f/listen",
  "type": "audio/mpeg",
  "homepage": "https://tuneindiaradio.com.au/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/tuneindiaradio.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Tune India Radio Bollywood is an online station from Sydney (Australia). Broadcasting was opened in 27th of June 2013. Listen to Bollywood content in quality 96 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "RadioCity",
  "date": "",
  "url": "https://radioindia.net/radio/cityco/icecast.audio",
  "type": "audio/mpeg",
  "homepage": "http://radiocityfm.co/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/radio-city.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'RadioCity is an online station from Wellington (New Zealand). Broadcasting was opened in 2012. Listen to Bollywood and pop content in quality 128 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio Hum 106.1 FM",
  "date": "",
  "url": "http://stream.zeno.fm/rfxzab5h3p8uv",
  "type": "audio/mpeg",
  "homepage": "https://sites.google.com/view/goldyfm/home",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/goldybhal.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Goldy Bhal is an online radio station from (India). Listen to Bollywood and talk content in quality 96kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Goldy Cool",
  "date": "",
  "url": "http://stream.zeno.fm/hhfmh86tfm8uv",
  "type": "audio/mpeg",
  "homepage": "https://zeno.fm/goldy-cool/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/goldycool.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Goldy Cool is an online radio station from Dholera (India). Listen to Bollywood and Love Songs content in quality 120 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Shri Hanuman Chalisa - Sandeep Khurana by Sandeep Khurana",
  "date": "",
  "url": "http://skivamusic.com/podcast/media/2012-01-23_shri_hanuman_chalisa_voice_sandeep_khurana_128.mp3",
  "type": "audio/mpeg",
  "homepage": "http://www.humfmradio.com",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/City-Ghazal.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": ``,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio BongOnet",
  "date": "",
  "url": "https://stream.bongonet.net/proxy/radiobongonet?mp=/stream",
  "type": "audio/mpeg",
  "homepage": "https://www.bongonet.net/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/Radio-BongOnetKolkata.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Radio BongOnet is an online station from Kolkata (India). Listen to pop content in quality 128 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "bengali",
  "languagecodes": "hi",
},
{
  "name": "Radio BongOnet Robichhaya",
  "date": "",
  "url": "https://stream.bongonet.net/proxy/robichhaya?mp=/stream",
  "type": "audio/mpeg",
  "homepage": "https://www.bongonet.net/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/robichhaya.jpg",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Radio BongOnet Robichhaya is an online station from Kolkata (India). Listen to classic content in quality 128 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "bengali",
  "languagecodes": "hi",
},
{
  "name": "Radio BongOnet Disco Bani",
  "date": "",
  "url": "https://stream.bongonet.net/proxy/discobanikolkata?mp=/stream",
  "type": "audio/mpeg",
  "homepage": "https://www.bongonet.net/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/DiscoBani-Kolkata-BongOnet.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Radio BongOnet Disco Bani is an online station from Kolkata (India). Listen to dance content in quality 128 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},
{
  "name": "Radio BongOnet MonoPhone",
  "date": "",
  "url": "https://stream.bongonet.net/proxy/monophone?mp=/stream",
  "type": "audio/mpeg",
  "homepage": "https://www.bongonet.net/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/bongonetphone.jpg",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Radio BongOnet MonoPhone is an online station from Kolkata (India). Listen to pop and Love Songs content in quality 128 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "bengali",
  "languagecodes": "hi",
},
{
  "name": "Radio BongOnet Folk Nama",
  "date": "",
  "url": "https://stream.bongonet.net/proxy/folknama?mp=/stream",
  "type": "audio/mpeg",
  "homepage": "https://www.bongonet.net/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/HN6HIY.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Radio BongOnet Folk Nama is an online station from Kolkata (India). Listen to folk content in quality 128 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "bengali",
  "languagecodes": "hi",
},
{
  "name": "Radio BongOnet Bangla Rock",
  "date": "",
  "url": "https://stream.bongonet.net/proxy/radiobanglarock?mp=/stream",
  "type": "audio/mpeg",
  "homepage": "https://www.bongonet.net/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/mobilebongonet.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Radio BongOnet Bangla Rock is an online station from Kolkata (India). Listen to rock content in quality 128 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "bengali",
  "languagecodes": "hi",
},
{
  "name": "Radio BongOnet Go YesterYears",
  "date": "",
  "url": "https://stream.bongonet.net/proxy/goyesteryears?mp=/stream",
  "type": "audio/mpeg",
  "homepage": "https://www.bongonet.net/",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/goyesteryears.jpg",
  "tags": "Hindi love, bollywood, love songs",
  "description": 'Radio BongOnet Go YesterYears is an online station from Kolkata (India). Listen to folk content in quality 128 Kbps in free live streaming.',
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "bengali",
  "languagecodes": "hi",
},
{
  "name": "Radio Hum 106.1 FM",
  "date": "",
  "url": "https://ice10.securenetsystems.net/HUMFM?playSessionID=ECACF786-A4F2-6C95-7BD7DCE1A730EE1A",
  "type": "audio/mpeg",
  "homepage": "http://www.humfmradio.com",
  "favicon": "https://onlineradiofm.in/assets/image/radio/180/City-Ghazal.png",
  "tags": "Hindi love, bollywood, love songs",
  "description": ``,
  "country": "India",
  "countrycode": "IN",
  "state": "New Delhi",
  "language": "hindi",
  "languagecodes": "hi",
},


]


module.exports.rawData = rawData;
